# Appium server URL (default port 4723)
appium.url=http://127.0.0.1:4723

# Android device / emulator name  (run: adb devices)
device.name=emulator-5554

# Android platform version
#platform.version=12.0

# Absolute path to the PFM APK on your machine
# Example Windows: C:/users/deepu/Downloads/PFM_Assignment.apk
app.path=C:/users/deepu/Downloads/PFM_Assignment.apk

# App package and launch activity
# Get these by running: aapt dump badging PFM_Assignment.apk
app.package=com.pfm.app
app.activity=.MainActivity
